### ISSUE TITLE
Change Wording for Robot Mesh Sponsorship

### ISSUE THREAD

**Issue by anncli** [esthermliu/exothermic-robotics#1]
Don't say we _have to_ do something in return. Instead be like _we do this because we are thankful for their support_. See example below:

Each year, we host the Exothermic Winter Challenge, which is sponsored by Robot Mesh and Northwest Tech Inc. Robot Mesh provides one free VRC Qualifying Event Trophy Pack for our event, and we also get a $100 store credit at Robot Mesh's website which can be used to buy any robot products. Robot Mesh also sends us Robot Mesh stickers for the competition and our club, which many of our teams use to decorate their robots. We are very thankful for what Robot Mesh's support so in return for what Robot Mesh does for us, we include the Robot Mesh logo on the event's sponsors list, and we also award their trophies at the Winter Challenge. Additionally, we also hand out Robot Mesh stickers to all of the teams, and send a list of the participating teams after the event.

Robot Mesh has sponsored our club for many years. We'd like to give a huge thank you to them for everything they've done!

**Comment by esthermliu** [comment]
Fixed 👍
