### ISSUE TITLE
Change wording for resources page

### ISSUE THREAD

**Issue by anncli** [esthermliu/exothermic-robotics#3]
- Change "we are one team overall" to "we collaborate together"
- Remove "so" from second sentence and change "here" to "this

One of our core values as a club is that we _collaborate together_ and therefore we help each other out. _This_ is the section where teams can submit their tips that they think could be beneficial to other teams and even other robotics clubs! To submit more tips, simply email: exothermictips@gmail.com.

**Comment by esthermliu** [comment]
Fixed 👍
