### ISSUE TITLE
Few Wording Changes for Resources

### ISSUE THREAD

**Issue by anncli** [esthermliu/exothermic-robotics#5]
Maybe don't say "do's and don'ts" for the building part because we that sounds like we are telling them what to do instead of giving them tips to guide them

Also change "coding tips" to "programming tips"

Also idk if you did this on purpose but the tab says "game tips" but the actual page says "competition tips". If possible can you change the tab to also say "competition tips"

**Comment by esthermliu** [comment]
Lol i originally named them that, but i changed them so they could be shorter bc it would lengthen out the dropdown tab, and make it look kinda weird.
