### ISSUE TITLE
Change Wording for When Do We Meet

### ISSUE THREAD

**Issue by anncli** [esthermliu/exothermic-robotics#8]
Original:
"Our official meetings are on Tuesdays and Thursdays, although often times, teams will meet multiple times a week _from 5:30 to 7:30 per week_, especially before competitions. Each team is given their own key to the space so they _more or less_ get to decide their own meeting schedules, creating a flexible environment. Each team also communicates with each other about who is at the _EXO_ house as well as other information, such as upcoming competitions, fees, etc."

New:
"Our official meetings are on Tuesdays and Thursdays _from 5:30 - 7:30 PM_, although often times, teams will meet multiple times a week, especially before competitions. Each team is given their own key to the space so they get to decide their own meeting schedules, creating a flexible environment. Each team also communicates with each other about who is at the _robot_ house as well as other information, such as upcoming competitions, fees, etc.

**Comment by esthermliu** [comment]
Fixed 👍
