### ISSUE TITLE
Change Wording for Where Do We Work

### ISSUE THREAD

**Issue by anncli** [esthermliu/exothermic-robotics#9]
Original:
"have our own workspace located just off of Willows Road in Redmond, Washington. Inside, we've set up a raised practice field as well as tables for each team to work on. We also have various boxes that hold metal and other materials that may be needed to build the robot."

New:
"We have our own workspace located just off of Willows Road in Redmond, Washington. Inside, we've set up a raised practice field as well as tables for each team to work on. _Teams share the basic supplies and tools needed to create an effective robot, but can also order their own parts when needed._"

**Comment by esthermliu** [comment]
Changed it 👍
